num_1= int(input("enter first number "))
num_2= int(input("enter second number "))
num_3= int(input("enter third number "))
average=((num_1+num_2+num_3)/3)
print(f"average of three number :",{average})